# Site title will be used everywhere
title: Riverscapes Analysis Visualization Explorer
description: > # this means to ignore newlines until "baseurl:"
  Online help and documentation site for the RAVE
remote_theme: Riverscapes/riverscapes-jekyll-theme
# Final root url of the site. No ending slash. No subdirectory
url: http://rave.riverscapes.xyz
# If the site is in a subdirectory you should do it like this: "/subdirectory". Otherwise ""
# baseurl: "/gcd"
# When serving locally what port should we use:
port: 4001
google_analytics: UA-60121403-8
# Markdown style
markdown: kramdown
# Syntax highlighter
highlighter: rouge

# Choosing "default" layout means we don't need a "layout:default" in all our 
# front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Files/Folders to exclude from publishing
exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml
  - Gemfile*


# These are theme settings that will be used to turn features on and off
# They are not part of Jekyll, they are entirely custom.
settings:
  # Turn the automatically generated page contents on and off
  autoPageContents:
    active: true
    onHome: false
  # Options for the sidebar menu      
  sideMenu:
    homeItem: true
    startExpanded: false
  # Arbitrary multi-level topbar menu
  # IF you don't need this just comment out everything below
  # ----------------------------------
  topmenu:
    - title: "Riverscapes"
      childern:
        - title: "Model Home"
          url: index
        - title: "Riverscapes Home"
          url: http://riverscapes.xyz
        - title: "About Riverscapes"
          url: http://riverscapes.xyz/about.html
        - title: "Who We Are"
          url: http://riverscapes.xyz/who-we-are.html
        - title: "News"
          url: http://riverscapes.xyz/news.html
    - title: "RC Tools"
      url: http://riverscapes.xyz/rc-tools.html
    - title: "RC Science"
      url: http://riverscapes.xyz/rc-science.html
    - title: "RC Data"
      url: http://riverscapes.xyz/rc-data.html
    - title: "RC Help"
      url: http://riverscapes.xyz/rc-help.html

# Redirecting from apps can be tricky so we use a key-value system
# key: must be in the set [A-Za-z0-9_] (no spaces, no dashes)
# url: must be relative url, no leading slash.
# 
# The url you have to call is: http://siteurl.com/baseurl/?APPKEY=KEY1
# ---------------------------------------------------------------
AppRedirects:
  - key: NewProject
    url: Help/Commands/project-menu/new-project.html
  - key: KEY2
    url: Download/release_notes.html
  - key: OpenProject
    url: Help/Commands/project-menu/open-project.html
  
plugins:
  - jekyll-remote-theme